using DotNetNuke.Data;
using DotNetNuke.Modules.Wiki.BusinessObjects.Models;
using System.Collections.Generic;

namespace DotNetNuke.Modules.Wiki.BusinessObjects
{
    public class ItemBO : _AbstractBusinessObject<Item, int>
    {
        private UnitOfWork _uof;

        public ItemBO(UnitOfWork uof)
            : base(uof.Context)
        {
            this._uof = uof;
        }

        #region Enums

        /// <summary>
        /// The possible controlled errors generated by this class
        /// </summary>
        public enum ItemError
        {
            Error1 = 1,
            Error2 = 2,
            Error3 = 3
        }

        #endregion Enums

        public override void Entity_EvaluateSqlException(System.Data.SqlClient.SqlException exc, Utilities.SharedEnum.CrudOperation crudOperation)
        {
            throw new System.NotImplementedException();
        }
    }
}