using DotNetNuke.Modules.Wiki.BusinessObjects.Models;

namespace DotNetNuke.Modules.Wiki.BusinessObjects
{
    public class ItemBO : _AbstractBusinessObject<Item, int>
    {
        #region Variables

        private UnitOfWork _uof;

        #endregion Variables

        #region Ctor

        public ItemBO(UnitOfWork uof)
            : base(uof.Context)
        {
            this._uof = uof;
        }

        #endregion Ctor

        #region Enums

        /// <summary>
        /// The possible controlled errors generated by this class
        /// </summary>
        public enum ItemError
        {
            Error1 = 1,
            Error2 = 2,
            Error3 = 3
        }

        #endregion Enums

        #region Methods

        internal override void Entity_EvaluateSqlException(System.Data.SqlClient.SqlException exc, Utilities.SharedEnum.CrudOperation crudOperation)
        {
            throw new System.NotImplementedException();
        }

        #endregion Methods
    }
}