'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4952
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Wiki.Controls

    Partial Public Class WikiMenu

        '''<summary>
        '''LinksPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LinksPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''HomeBtn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HomeBtn As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''SearchBtn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SearchBtn As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''RecChangeBtn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RecChangeBtn As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''IndexBtn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents IndexBtn As Global.System.Web.UI.WebControls.HyperLink
    End Class
End Namespace
