'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Wiki

    Partial Public Class Administration

        '''<summary>
        '''SecuritySettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SecuritySettings As Global.System.Web.UI.UserControl

        '''<summary>
        '''DNNSecurityChk control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DNNSecurityChk As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''WikiSecurity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents WikiSecurity As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblNotifyMethodEditRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotifyMethodEditRoles As Global.System.Web.UI.UserControl

        '''<summary>
        '''NotifyMethodEditRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NotifyMethodEditRoles As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblNotifyMethodViewRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotifyMethodViewRoles As Global.System.Web.UI.UserControl

        '''<summary>
        '''NotifyMethodViewRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NotifyMethodViewRoles As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblNotifyMethodCustomRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotifyMethodCustomRoles As Global.System.Web.UI.UserControl

        '''<summary>
        '''NotifyMethodCustomRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NotifyMethodCustomRoles As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblNotifyRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotifyRoles As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblAllowPageComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllowPageComments As Global.System.Web.UI.UserControl

        '''<summary>
        '''AllowPageComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AllowPageComments As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblActivateComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblActivateComments As Global.System.Web.UI.UserControl

        '''<summary>
        '''ActivateComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ActivateComments As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblDefaultCommentsMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDefaultCommentsMode As Global.System.Web.UI.UserControl

        '''<summary>
        '''DefaultCommentsMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DefaultCommentsMode As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblNotifyMethodUserComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotifyMethodUserComments As Global.System.Web.UI.UserControl

        '''<summary>
        '''NotifyMethodUserComments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NotifyMethodUserComments As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblAllowPageRatings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllowPageRatings As Global.System.Web.UI.UserControl

        '''<summary>
        '''AllowPageRatings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AllowPageRatings As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblActivateRatings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblActivateRatings As Global.System.Web.UI.UserControl

        '''<summary>
        '''ActivateRatings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ActivateRatings As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblDefaultRatingMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDefaultRatingMode As Global.System.Web.UI.UserControl

        '''<summary>
        '''DefaultRatingMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DefaultRatingMode As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''SaveButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SaveButton As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''CancelButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CancelButton As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
