'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Wiki

    Partial Public Class RecentChanges

        '''<summary>
        '''TitleLbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TitleLbl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''HitTable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HitTable As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''cmdLast24Hrs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdLast24Hrs As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdLast7Days control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdLast7Days As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdLastMonth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdLastMonth As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
