'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Wiki

    Partial Public Class Start

        '''<summary>
        '''lblPageTopic control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPageTopic As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''CommentCount1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CommentCount1 As Global.DotNetNuke.Modules.Wiki.Comments.CommentCount

        '''<summary>
        '''lblPageContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPageContent As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''ratingTbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ratingTbl As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''CommentsTbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CommentsTbl As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''AddCommentCommand control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AddCommentCommand As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''Comments2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Comments2 As Global.DotNetNuke.Modules.Wiki.Comments.Comments

        '''<summary>
        '''AddCommentPane control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AddCommentPane As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''PostCommentLbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PostCommentLbl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''AddCommentsForm1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AddCommentsForm1 As Global.DotNetNuke.Modules.Wiki.Comments.AddCommentsForm
    End Class
End Namespace
