'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4016
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Wiki

    Partial Public Class Ratings

        '''<summary>
        '''pnlCastVote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCastVote As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''RatingsTable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RatingsTable As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''RatePagelbl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RatePagelbl As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''LowRating control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LowRating As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rating1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rating1 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rating2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rating2 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rating3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rating3 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rating4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rating4 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rating5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rating5 As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''HighRating control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents HighRating As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlVoteCast control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlVoteCast As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblVoteCastMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVoteCastMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAverageRatingMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAverageRatingMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAverageRating control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAverageRating As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''RatingsGraphTable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RatingsGraphTable As Global.System.Web.UI.WebControls.Table

        '''<summary>
        '''lblRatingCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRatingCount As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
